version: '3'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - '9000:9000'

  database:
    image: 'mongo'
    container_name: MONGODB
    ports:
      - '27017:27017'
    volumes:
      - ./data/database:/data/database
