version: '3.1'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - ./:/jwt-node
      - ./node_modules:/jwt-node/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - ${PORT}:${PORT}

  database:
    image: 'mongo'
    container_name: MONGODB
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./data/database:/data/database
